# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11i4wA7i2ZtbsoPIft5abyr3oUwKyS2LT
"""

import numpy as np
import math
from matplotlib import pyplot as plt

#Generating points on a circle
def circ_gen(O,r):
	len = 50
	theta = np.linspace(0,2*np.pi,len)
	x_circ = np.zeros((2,len))
	x_circ[0,:] = r*np.cos(theta)
	x_circ[1,:] = r*np.sin(theta)
	x_circ = (x_circ.T + O).T
	return x_circ



#input parameters
C = np.array([3,2])
O = np.array([0,0])
P1 = np.array([3,0])
P2 = np.array([15/13,36/13])


r=2 #from question
x_circ= circ_gen(C,r)
plt.plot(x_circ[0,:],x_circ[1,:])
#plotting the lines
a= (np.array(([O,P1]))).T
plt.plot(a[0,:],a[1,:])
b= (np.array(([O,P2]))).T
plt.plot(b[0,:],b[1,:])
#plotting the points
plt.plot(O[0], O[1], 'o')
plt.text(O[0] * (1 + 0.3), O[1] * (1 + 0.01) , 'O')
plt.plot(P1[0], P1[1], 'x')
plt.text(P1[0] * (1 + 0.1), P1[1] * (1) , 'P1')
plt.plot(P2[0],P2[1], 'x')
plt.text(P2[0]* (1 + 0.1) , P2[1] * (1) , 'P2')
plt.plot(C[0],C[1],'o')
plt.text(C[0] * (1 + 0.01), C[1] * (1 + 0.03) , 'C')
plt.grid()
angle = math.degrees(math.atan((12/5 - 0)/1+ 12/5*0))
print("Angle subtended:",angle)