# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jftxx89dYKbNoNpRyRQSyNnZJGg9T-uX
"""

# importing the required modules
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
fig, ax = plt.subplots()
# setting the x - coordinates
x = np.arange(-20, 30, 0.1)
# setting the corresponding y - coordinates
y = (x-2)/((x-2)**2 + 2**2)

label = plt.axvline(x=2,label="x=a")
'''x1= 2
y1 = np.arange(-20, 30, 0.1)'''
# plotting the points
plt.plot(x, y,'r')
'''plt.plot(x1,y1)'''
plt.xlim(-20,30)
plt.annotate("a", (2, 0))
line1 = 2 # vertical x = 3
line2 = 50 # vertical x = 5

ax.axvspan(line1, line2, alpha=.5, color='blue')
patches = mpatches.Patch(color="blue", label="ROC")
plt.legend(handles=[patches,label], loc = 'upper right')
plt.xlabel("Re{s}")
plt.ylabel("jW")
# function to show the plot
plt.grid()
plt.show()