# -*- coding: utf-8 -*-
"""GATE_ASSIGNMENT_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TUswLZxhxY9DcJf7UOkFvc_-5OzSoK9N
"""

import numpy as np
from matplotlib import pyplot as plt

time = np.arange(-10,10,0.01)
e2 = np.exp(-2*time)
e1 = np.exp(-1*time)
e3 = np.exp(-3*time)
def unit(time):
  a=[]
  for i in time:
    if i<0:
      a.append(0)
    else:
      a.append(1)
  return a 

## input x(t)
def X(time):
  a=[]
  for i in time:
    if i<0:
      a.append(0)
    else:
      a.append(2)
  return a 

y = (e1-2*e2+1)*unit(time)
plt.plot(time,X(time),label='x(t)')
plt.plot(time,y,label='y(t)')
plt.xlabel('Time')
plt.grid()
plt.legend()